version: '3.8'
services:
  gateway:
    build: shareit-gateway
    image: shareit-gateway-image
    container_name: shareit-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: shareit-server
    image: shareit-server-image
    container_name: shareit-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iamroot
  db:
    image: postgres:16-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shareit